export const ADD_SEARCH_STRING      = 'ADD_SEARCH_STRING';
export const FETCH_CURRENT_WEATHER  = 'FETCH_CURRENT_WEATHER';
export const FETCH_SHORT_FORECAST   = 'FETCH_SHORT_FORECAST';
export const FETCH_LONG_FORECAST    = 'FETCH_LONG_FORECAST';